name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Create Android project files
        run: flutter create .
        
      - name: Set Android minimum SDK
        run: sed -i 's/minSdk = flutter.minSdkVersion/minSdk = 23/' android/app/build.gradle.kts
        
      - name: Add AdMob App ID
        run: |
          sed -i '/<application/i\        <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-3600725386955734~3134884048"/>' android/app/src/main/AndroidManifest.xml
          
      - name: Remove default Flutter test
        run: rm -rf test
  
      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: cashpeak-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
